{% set name = "include-what-you-use" %}
{% set version = "0.20" %}
{% set llvm_version = "16.*" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 4fe4bd5581ee60bb2bcf1bf40f087a8c5b090d943d0376233638f30f29af0e2e

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - python
  host:
    - clangdev {{ llvm_version }}
    - llvmdev {{ llvm_version }}
    - llvm {{ llvm_version }}
    - libclang-cpp {{ llvm_version }}
    - lld {{ llvm_version }}
  run:
    - python  # [win]
test:
  commands:
    - {{ name }} --version
    - {{ name }} --help

about:
  home: https://include-what-you-use.org
  summary: 'A tool for use with clang to analyze #includes in C and C++ source files'
  description: |
    "Include what you use" means this: for every symbol (type, function, variable, or macro)
    that you use in foo.cc (or foo.cpp), either foo.cc or foo.h should include a .h file that
    exports the declaration of that symbol. (Similarly, for foo_test.cc, either foo_test.cc or foo.h
    should do the including.) Obviously symbols defined in foo.cc itself are excluded from this requirement.
  license: NCSA  # University of Illinois/NCSA Open Source
  license_family: OTHER  # NCSA
  license_file: LICENSE.TXT
  doc_url: https://include-what-you-use.org
  dev_url: https://github.com/include-what-you-use/include-what-you-use

extra:
  recipe-maintainers:
    - xmnlab
    - xylar
